name: commander_ui
description: Commander is a Dart library for creating user interfaces within the terminal.
version: 1.2.0
repository: https://github.com/LeadcodeDev/commander

topics:
  - cli
  - tui

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  mansion: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
