name: commander
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/LeadcodeDev/commander

environment:
  sdk: ^3.0.6

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
